image:
  file: .gitpod.dockerfile
  context: apache
ports:
- port: 8080
  onOpen: open-preview
tasks:
- name: Terminal
  command: >
    echo "Servidor iniciado...";
- name: Apache
  command: >
    apachectl start
